new file:   css/bootstrap.css
simvyc/CA_travel_web_page pull request #1
Opened 2022-09-05 19:01 UTC by simvyc

new file:   css/style.css
	new file:   index.html
	new file:   js/bootstrapValidator.js
	new file:   js/js.js
	new file:   js/jumbotron.css
	new file:   pictures/background/background.jpg
	new file:   pictures/background/white_carbon.jpg
	new file:   pictures/countries/argentina.jpg
	new file:   pictures/countries/egypt.jpg
	new file:   pictures/countries/england.jpg
	new file:   pictures/countries/england1.jpg
	new file:   pictures/countries/estonia.jpg
	new file:   pictures/countries/france.jpg
	new file:   pictures/countries/france1.jpg
	new file:   pictures/countries/havaii.jpg
	new file:   pictures/countries/havaii1.jpg
	new file:   pictures/countries/latvia.jpg
	new file:   pictures/countries/lithuania.jpg
	new file:   pictures/countries/lithuania1.jpg
	new file:   pictures/countries/norway.jpg
	new file:   pictures/countries/peru.jpg
	new file:   pictures/countries/peru1.jpg
	new file:   pictures/countries/slovenia.jpg
	new file:   pictures/countries/switzerland.jpg
	new file:   pictures/countries/switzerland1.jpg
	new file:   pictures/countries/usa.jpg
	new file:   pictures/countries/usa1.jpg
	new file:   pictures/logo/logo1.png
	new file:   pictures/logo/logo3.png
	new file:   pictures/pexels_image_world.jpg
	new file:   templates/about.html
	new file:   templates/contact.html
	new file:   templates/lithuania.html
	new file:   templates/travels.html
	new file:   travel_web_page

2022-09-08 18:41 UTC, MantasSkara commented on index.html
> +  <body background="../CA_travel_web_page/pictures/background/white_carbon.jpg">
Kodėl ne tiesiog href="pictures/background/white_carbon.jpg" ? 

index.html yra tom pačiam levelyje kaip ir pictures

2022-09-08 18:43 UTC, MantasSkara commented on index.html
> +            <p><a class="btn btn-info" href="../CA_travel_web_page/templates/contact.html" role="button">Contact us</a></p>
Kartojasi visur.

2022-09-08 18:46 UTC, MantasSkara requested changes
Matosi, kad daug darbo įdėta, tai šauniai tikrai :) Keleta pastabų dėl nuorodu turiu, keletas href'u neveikia

2022-09-11 19:33 UTC, simvyc commented on index.html
> +            <p><a class="btn btn-info" href="../CA_travel_web_page/templates/contact.html" role="button">Contact us</a></p>
Ištaisiau

2022-09-12 16:39 UTC, MantasSkara approved these changes
Good job 👍  Nepastebėjau kažkokių klaidų, gal kažkur nuorodų formatavimas galėtų vienos stilistikos laikytis, bet apart to viskas kaip ir good :) Pridedu Vakarį prie reviewers užkart

2022-09-21 18:10 UTC, VakarisZ commented on index.html
> +      </div>
Truksta vieno `</div>`

2022-09-21 18:29 UTC, VakarisZ commented on templates/travels.html
> +              <td><img src="../pictures/countries/france1.jpg" class="img-fluid img-thumbnail" width="200" ></img></td>
Kodel "width" neidejai i stiliu faila?

2022-09-21 18:33 UTC, VakarisZ reviewed
+ rep, kad panaudojai bootstrapa
- rep, kad mažokai CSS ir JS

2022-09-21 18:34 UTC, VakarisZ commented on templates/contact.html
> +    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-info">
Kodėl taip arti krašto? 
![image](https://user-images.githubusercontent.com/36815064/191583716-ea47d8fa-b8c9-4bdd-8ab5-762e3deb6c08.png)

2023-04-24 18:06 UTC, merged